version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.17.5
    steps:
      - checkout
      - run:
        name: Checking code
        command: |
          echo 'Checking code integrity'
          ls -la
      - run:
        name: Checking node version
        command: |
          echo 'Now checking node version...'
          node -v
      - run:
          name: Installing dependencies
          command: |
            echo 'Now building...'
            npm run build
      - run:
          name: Building
          command: |
            echo 'Now building IdylisAPI...'
            npm run build
  test:
    docker:
      - image: circleci/node:14.17.5
    steps:
      - checkout
      - run:
          name: Installing dependencies & starting tests
          command: npm install && npm run test:dev
workflows:
  version: 2
  idylisapi_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
